// ─── PAYER REQUIREMENTS & CATALOG ───────────────────────────────────────────
// PAYER_REQUIREMENTS: credentialing requirements per payer (never changes at runtime)
// PAYER_CATALOG: payer directory used in PayerModal picker
// REQUIRED_DOCS: document compliance rules used in MissingDocuments

const PAYER_CATALOG = [
  { name:'Aetna', payerId:'60054', type:'Commercial', phone:'1-800-872-3862', portal:'https://www.availity.com', timeline:'60–90 days', color:'#C8102E',
    notes:'Submit via Availity. CAQH must be attested within last 120 days. Group and individual enrollment both required.',
    guidelines:['Complete CAQH profile (attested within 120 days)','Submit application via Availity portal','Include NPI Type 1 and Type 2','Provide current CV/Resume','Attach copy of state license','Attach malpractice insurance certificate','Include W-9 form','DEA certificate if prescribing'],
    warn:'Group enrollment is separate from individual — submit both if billing under a group NPI.' },
  { name:'BCBS Oregon (Regence)', payerId:'00550', type:'Commercial', phone:'1-800-452-7278', portal:'https://www.regence.com/providers', timeline:'45–60 days', color:'#00539F',
    notes:'OHA/Medicaid participation often recommended first for behavioral health. Contact Provider Relations for behavioral health contracts.',
    guidelines:['Complete CAQH profile','Submit Regence provider application (paper or portal)','Include state license copy','Include malpractice insurance certificate','Include W-9 form','NPI Type 1 required','CV/Resume required'],
    warn:'For behavioral health: OHA enrollment is recommended before applying to Regence.' },
  { name:'OHP / Medicaid (OHA)', payerId:'OROHP', type:'Medicaid', phone:'1-800-273-0557', portal:'https://www.oregon.gov/oha/hsd/ohp', timeline:'45–60 days', color:'#2d6a4f',
    notes:'Oregon Health Plan enrollment through DMAP. Supervising provider must also be enrolled if applicable.',
    guidelines:['Complete DMAP enrollment form (via OHA portal)','Provide Oregon license copy','Include malpractice insurance certificate','W-9 form required','NPI Type 1 required','Background check authorization','Medicaid Provider Agreement','Supervising provider must be enrolled separately'],
    warn:'Associates/interns under supervision: the supervising clinician must be enrolled in OHP first.' },
  { name:'Cigna / Evernorth', payerId:'62308', type:'Commercial', phone:'1-800-735-1459', portal:'https://cignaforhcp.cigna.com', timeline:'60–90 days', color:'#004B87',
    notes:'Submit via Cigna for Health Care Professionals portal. Mental health providers may route through Evernorth. CAQH must be complete.',
    guidelines:['Complete CAQH profile','Submit via Cigna for Health Care Professionals portal','NPI Type 1 and Type 2','Current CV/Resume','State license copy','Malpractice insurance certificate','W-9 form','DEA if prescribing'],
    warn:'Mental health and substance use providers: contact Evernorth Behavioral Health separately for network participation.' },
  { name:'UnitedHealthcare / Optum', payerId:'87726', type:'Commercial', phone:'1-877-842-3210', portal:'https://www.providerexpress.com', timeline:'60–120 days', color:'#006699',
    notes:'Mandatory revalidation every 3 years — failure results in termination. Behavioral health credentialing through Optum/Provider Express.',
    guidelines:['Complete CAQH profile','Submit via Provider Express (providerexpress.com)','NPI Type 1 and Type 2','Current CV/Resume','State license copy','Malpractice insurance certificate','W-9 form','Revalidation form if revalidating'],
    warn:'⚠ Revalidation every 3 years is MANDATORY. Missing the revalidation window results in automatic termination from the network.' },
  { name:'Providence Health Plan', payerId:'93029', type:'Commercial', phone:'1-800-891-2803', portal:'https://www.providence.org/providers', timeline:'45–75 days', color:'#0061A1',
    notes:'Oregon-specific payer with strong Portland metro presence. Contact Provider Relations directly for application packets.',
    guidelines:['Submit Providence provider application','Include state license copy','Include malpractice insurance certificate','W-9 form','NPI Type 1','CV/Resume','CAQH profile','Contact Provider Relations for application packet'],
    warn:null },
  { name:'Moda Health', payerId:'MODA1', type:'Commercial', phone:'1-855-718-1768', portal:'https://www.modahealth.com/medical/provider', timeline:'30–60 days', color:'#C41E3A',
    notes:'Oregon-based regional payer. Behavioral health credentialing handled directly by Moda. Often faster than national payers.',
    guidelines:['Submit Moda provider application (portal or paper)','State license copy','Malpractice insurance certificate','W-9 form','NPI Type 1','CAQH profile','CV/Resume'],
    warn:null },
  { name:'PacificSource Health Plans', payerId:'93015', type:'Commercial', phone:'1-888-977-9299', portal:'https://www.pacificsource.com/providers', timeline:'30–60 days', color:'#0033A0',
    notes:'Northwest regional payer covering Oregon, Idaho, and Montana. Direct application process.',
    guidelines:['Submit PacificSource provider application','State license copy','Malpractice insurance certificate','W-9 form','NPI Type 1','CV/Resume','Contact Provider Relations for current application form'],
    warn:null },
  { name:'Kaiser Permanente', payerId:'94456', type:'Commercial', phone:'1-800-813-2000', portal:'https://providers.kaiserpermanente.org', timeline:'90–120 days', color:'#003781',
    notes:'INVITATION ONLY — closed panel in most markets. Contact Network Relations to inquire about open panels.',
    guidelines:['Receive invitation from Kaiser Network Relations','Complete Kaiser credentialing application','CAQH profile required','Board certification may be required','State license copy','Malpractice insurance certificate','W-9 form','NPI Type 1'],
    warn:'⚠ Kaiser is an invitation-only, closed panel network. Do not apply without first confirming an open panel with Network Relations.' },
  { name:'Humana', payerId:'61101', type:'Commercial', phone:'1-800-626-2741', portal:'https://www.humana.com/provider', timeline:'60–90 days', color:'#006F44',
    notes:'Submit via Availity or Humana Provider Portal. Behavioral health may route through Humana Behavioral Health.',
    guidelines:['Complete CAQH profile','Submit via Availity or Humana provider portal','NPI Type 1 and Type 2','State license copy','Malpractice insurance certificate','W-9 form','CV/Resume'],
    warn:'Behavioral health providers: confirm whether enrollment routes through Humana Behavioral Health or main credentialing.' },
  { name:'Anthem / Elevance Health', payerId:'00530', type:'Commercial', phone:'1-800-676-2583', portal:'https://www.anthem.com/provider', timeline:'60–90 days', color:'#0079C1',
    notes:'Operates as Elevance Health nationally. Behavioral health credentialing through Beacon Health Options in some markets.',
    guidelines:['Complete CAQH profile','Submit via Availity or Anthem provider portal','NPI Type 1 and Type 2','State license copy','Malpractice insurance certificate','W-9 form','CV/Resume'],
    warn:'Behavioral health providers: Beacon Health Options manages behavioral health credentialing in some Anthem markets — verify routing.' },
  { name:'Molina Healthcare', payerId:'MOLIN', type:'Medicaid', phone:'1-888-665-4621', portal:'https://www.molinahealthcare.com/providers', timeline:'45–75 days', color:'#007DC3',
    notes:'Medicaid-focused MCO. OHP enrollment often required first. Background check required.',
    guidelines:['Enroll in OHP/Medicaid first (recommended)','Complete Molina provider application','W-9 form','State license copy','Malpractice insurance certificate','NPI Type 1','Medicaid Provider Agreement','Background check authorization'],
    warn:'OHP/DMAP enrollment is strongly recommended before applying to Molina, as Molina serves the OHP population.' },
  { name:'Medicare (Novitas/CGS)', payerId:'MDCR1', type:'Medicare', phone:'1-855-252-8782', portal:'https://pecos.cms.hhs.gov', timeline:'60–90 days', color:'#1B3A6B',
    notes:'Medicare enrollment through PECOS. CMS-855 application required. Opt-out available for some provider types.',
    guidelines:['Enroll via PECOS (pecos.cms.hhs.gov)','Complete CMS-855 application form','State license copy','Malpractice insurance certificate','NPI Type 1','W-9 form','Background check authorization','Assign/reassign benefits if billing under group'],
    warn:'Providers who do not accept Medicare must formally opt-out via CMS. Failing to enroll or opt-out may result in claims issues.' },
  { name:'Medicare Advantage (various)', payerId:'', type:'Medicare Advantage', phone:'', portal:'', timeline:'60–90 days', color:'#374151',
    notes:'Each Medicare Advantage plan credentials separately. Common MA plans in Oregon: UHC MA, Aetna MA, Humana MA, Kaiser MA.',
    guidelines:['Enroll in Medicare (Part B) first via PECOS','Apply to each MA plan separately','CAQH profile generally required','State license copy','Malpractice insurance certificate','NPI Type 1','W-9 form'],
    warn:'Medicare Advantage credentialing is separate from traditional Medicare — you must apply to each MA plan individually.' },
  { name:'TRICARE (West – Health Net)', payerId:'TRIC1', type:'Commercial', phone:'1-844-866-9378', portal:'https://www.tricare.mil/providers', timeline:'60–90 days', color:'#003087',
    notes:'Oregon is in the TRICARE West region, managed by Health Net Federal Services.',
    guidelines:['Submit TRICARE application via Health Net Federal Services','State license copy','Malpractice insurance certificate','NPI Type 1','W-9 form','CV/Resume','Board certification preferred'],
    warn:'Oregon is TRICARE West — contact Health Net Federal Services, not Humana Military (which manages TRICARE East).' },
  { name:'Oscar Health', payerId:'OSCAR', type:'Commercial', phone:'1-855-672-2788', portal:'https://www.hioscar.com/providers', timeline:'45–75 days', color:'#EF4923',
    notes:'Growing Oregon presence. Technology-forward submission process. Check panel availability before applying.',
    guidelines:['Submit application via Oscar provider portal','State license copy','Malpractice insurance certificate','NPI Type 1','CAQH profile','W-9 form','CV/Resume'],
    warn:'Confirm open panels in your area before applying — Oscar is still expanding its Oregon network.' },
  { name:'First Choice Health', payerId:'FCHP1', type:'Commercial', phone:'1-800-231-6935', portal:'https://www.fchn.com/providers', timeline:'30–60 days', color:'#008080',
    notes:'Pacific Northwest regional network. Often used as a leased network by other payers in the region.',
    guidelines:['Submit First Choice Health application','State license copy','Malpractice insurance certificate','NPI Type 1','W-9 form','CV/Resume'],
    warn:null },
  { name:'Multiplan / PHCS', payerId:'MPLAN', type:'Commercial', phone:'1-800-950-7040', portal:'https://www.multiplan.com/providers', timeline:'30–45 days', color:'#6B21A8',
    notes:'Leased network accessed by many self-funded employer plans. Joining Multiplan expands reach significantly.',
    guidelines:['Submit Multiplan network application','State license copy','Malpractice insurance certificate','NPI Type 1','W-9 form','CV/Resume','Current CAQH profile'],
    warn:null },
]

const REQUIRED_DOCS = [
  { key: 'license', field: 'licenseExp', label: 'State License', severity: 'error' },
  { key: 'malpractice', field: 'malExp', label: 'Malpractice Insurance', severity: 'error' },
  { key: 'w9', field: null, label: 'W-9 Form', checkFn: (p, docs) => docs.some(d => d.provId === p.id && d.type === 'W-9'), severity: 'error' },
  { key: 'caqh', field: 'caqh', label: 'CAQH Number on File', checkFn: (p) => !!p.caqh, severity: 'warn' },
  { key: 'caqhAttest', field: 'caqhDue', label: 'CAQH Attestation Due', severity: 'warn' },
  { key: 'dea', field: null, label: 'DEA Certificate', checkFn: (p) => !p.dea || !!p.deaExp, severity: 'warn', skipIf: (p) => !p.dea },
  { key: 'npi', field: null, label: 'NPI Number', checkFn: (p) => !!p.npi, severity: 'error' },
  { key: 'recred', field: 'recred', label: 'Recredentialing Date Set', severity: 'warn' },
  { key: 'supAgreement', field: null, label: 'Supervision Agreement', checkFn: (p, docs) => !p.supervisor || docs.some(d => d.provId === p.id && d.type === 'Supervision Agreement'), severity: 'warn', skipIf: (p) => !p.supervisor },
]


export { PAYER_CATALOG, REQUIRED_DOCS }
